### ISSUE TITLE
app.module.ts contains private key

### ISSUE THREAD

**Issue by katoba86** [neew-gen/shop-app-server#1]
app.module.ts contains your private key... really?

**Comment by neew-gen** [comment]
Yes, when I did the push, I realized that the push private key and I have
to recreate the application in firebase. There's nothing important stored
there and I put it off for later...

ср, 9 июн. 2021 г. в 21:40, Kai Willam ***@***.***>:

**Comment by neew-gen** [comment]
fixed.
